### ISSUE TITLE
import doesn't seem to be working

### ISSUE THREAD

**Issue by hallzy** [marcobambini/gravity#32] opened 2017-03-07 19:51 UTC
I have tried some simple code with the import, and it did not work, so I went to write a testcase, but the testcase actually works and passes...

Consider the testcase:

```
import "../test.gravity"

#unittest {
  name: "Test Adding Values to a List";
  error: NONE;
  result: "testtesttest";
};

func main() {
  return test();
}
```

and then consider this regular file:

```
import "../test.gravity"

func main() {
  return test();
}
```

where the contents of ../test.gravity are:

```
func test() {
  return "testtesttest";
}
```

Running the testcase yields this result:

```
  $ gravity-unittest .
==============================================
Gravity UnitTest
Gravity version 0.2.5
Build date: Mar  7 2017
==============================================

1	Test file: mytest.gravity
	Test path: ./mytest.gravity
	Test Import
	SUCCESS


==============================================
Total Tests: 1
Total Successes: 1
Total Failures: 0
Result: 100.00 %
Time: 0.4988 ms
==============================================
```

But just running the regular file:

```
  $ gravity mytest.gravity 
SYNTAX ERROR on 0 (1,8): Unable to load file because no loadfile callback registered in delegate.
gravity: src/cli/gravity.c:160: main: Assertion `closure' failed.
Aborted (core dumped)
```

**Comment by marcobambini** [comment] 2017-03-07 21:25
The problem is that delegate (which is responsible to load the file) is not set, that's the reason why a SYNTAX ERROR is produced. Application should terminate before the assertion. I'll take a look at this issue.

**Comment by marcobambini** [comment] 2017-03-08 07:46
@hallzy I just committed a new version of the gravity command line app.
It is now able to handle the import statement via a load_file callback.
Please note that in this very simple example only files placed in the same folder as the executable work but I added explanations about how to support full loading.

**Closed by marcobambini** 2017-03-08 07:46 UTC
