### ISSUE TITLE
Issues & a couple questions regarding Gravity

### ISSUE THREAD

**Issue by ThatTonybo** [marcobambini/gravity#312] opened 2020-07-16 05:10 UTC
Long-term JavaScript user here, coming to see if there's anything better to learn. I love the look of Gravity and I'm willing to get dirty in it. I cloned it and went to run `make` but ran into this issue:
```
PS C:\gravity> make
cc -Isrc/compiler/ -Isrc/runtime/ -Isrc/shared/ -Isrc/utils/ -Isrc/optionals/ -std=gnu99 -fgnu89-inline -fPIC -DBUILD_GRAVITY_API -O2   -c -o src/compiler/gravity_ast.o src/compiler/gravity_ast.c
process_begin: CreateProcess(NULL, cc -Isrc/compiler/ -Isrc/runtime/ -Isrc/shared/ -Isrc/utils/ -Isrc/optionals/ -std=gnu99 -fgnu89-inline -fPIC -DBUILD_GRAVITY_API -O2 -c -o src/compiler/gravity_ast.o src/compiler/gravity_ast.c, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [src/compiler/gravity_ast.o] Error 2
```

I also have two questions regarding Gravity:
1. I saw a couple issues/pull requests regarding HTTP support. Is it ready and implemented yet, and if not, when is it expected to be ready?
2. Is there plans to add WebSocket and/or WebSocket Secure (ws/wss) support?

Thank you.

**Comment by marcobambini** [comment] 2020-11-06 16:39
Seems like the issue is in your system. Something is probably not installed correctly or missed.
You could try with gmake that should work better on Windows.

In the short-term I do not plan to add HTTP nor WebSocket to the core engine.
I close this issue but please let me know if you need more assistance.

**Closed by marcobambini** 2020-11-06 16:39 UTC
