### ISSUE TITLE
Questions regarding syntax

### ISSUE THREAD

**Issue by untoldengine** [marcobambini/gravity#384] opened 2022-02-22 06:51 UTC
Hi @marcobambini, hope you are doing well.

I have two questions.

1. I'm going through your documentations and came across Gravity feature that allows you to add a method during runtime using
"bind". The examples in your docs shows the following:

```
obj.bind("f2", {System.print("Hello from f2");});
obj.f2();    // Output: Hello from f2
```

My question is, what would the syntax be if your method/function 'f2' has parameters?

2. Just wondering about Gravity features/improvement roadmap. More specifically with the Error Messaging system. For example. I've noticed, that if I have multiple gravity script files, the error message only provides a line number, but it does not mention the file name that contains the error. Being able to know which file has the error will be so useful.

Thanks

**Comment by marcobambini** [comment] 2022-02-22 13:31
Hi @untoldengine:

1. The syntax is exactly the same, you just need to set the function name and then you can call it with any parameter. In your example: `obj.bind("f2", ....);
obj.f2(param1, param2, param3);`
2. to identify the file that generates the error, the struct`error_desc_t` contains a fileid field. You can associate fileid with a filename/path in the gravity_loadfile_callback which is automatically called each time an `#include` statement is executed.

Hope this helps!

**Comment by untoldengine** [comment] 2022-02-23 14:37
Hi @marcobambini 

Ok, thanks.
One more question. 

What is the proper way to clear the content of a gravity map? 

In my engine code, I'm creating a new gravity-map using:

`gravity_map_new(...)`

In another function, I load data into the map using:

`gravity_map_insert(...)`

After I have used the data, I want to clear the content of the map. I'm using this function:

`gravity_hash_remove(...) //I'm passing my map as the argument `

However, I don't know if that is right, since after a while, the system crashes. It seems that I am not properly clearing the content of the map. 

So, what is the proper way to clear the content of a map?

Thanks

**Comment by marcobambini** [comment] 2022-02-24 10:30
Hi @untoldengine,
Do you have a simple test case that is able to reproduce the crash?
Can you please share the code you use to clear the content of the map?
I could add a `gravity_reset` function to clear the content of a map.

**Comment by untoldengine** [comment] 2022-02-24 14:23
Hi @marcobambini 

Basically, what I would like to confirm is if the function in gravity:

`gravity_hash_remove(...)`

is similar to the function in C++ which clears a map's content.

`map::clear()`

If not, is there a function in gravity that does that?

Is hard to reproduce the bug, but I've seen it often enough that I am sure I am not clearing the content of the map properly.

Thank you

**Comment by untoldengine** [comment] 2022-02-24 23:56
Hi @marcobambini,

I did more testing this morning and it seems that the crash has nothing to do with the map's content not being cleared. The issue is that the GC is cleaning up objects which are still used in the game.

Here is a video showing what is going on (https://youtu.be/r1cYR99r5Hc)

1. At some point during gameplay, the function `gravity_gc_start()` is called. Meaning that the GC started its cleaning process.
2. Right after the GC was initiated, I get a 'BAD_ACCESS' error when this function is called `gravity_class_lookup()`

If you see the video, you will see that the gravity_class_t instance's content is all null.

This makes total sense. Gravity is cleaning up the game objects, but it has no idea which objects to clean up and which one not to.

So, the main question is: Is there a way to tell the GC which objects not to clean up?

I was thinking of setting the value of vm to null when creating an instance of gravity. For example:

```
//vm in this case is Null
gravity_instance_t *instance = gravity_instance_new(Null, c);
```

That way, the newly allocated object is not transfer to the VM and I have full ownership of its lifetime.

However, I don't know if that is safe at all.

**Comment by marcobambini** [comment] 2022-02-25 07:27
Hi @untoldengine,

Based on your description (and your video), it is likely that the crash is due to an object already cleaned up by the GC.
The trick to exclude an object from the GC is to not call the function `gravity_vm_transfer`, which happens when you pass NULL as the VM parameter of the `gravity_instance_new` function.

This trick should solve your issue, but it gives you the task to manually free that instance/object.

I'd like to know now the real cause of the crash.
It could be an issue in your code (an allocated object with a Null VM then deallocated by the GC) or a bug in my GC code.

Any other detail would be really useful.

P.S. just in case you need more control over the GC, please note that you can temporarily stop/start it using the `gravity_gc_setenabled` function.

**Comment by untoldengine** [comment] 2022-02-25 13:16
Hi @marcobambini 

Good news!!! 

So I excluded the objects from being cleaned by the GC and the engine ran fine for almost an hour. So, I think the trick fixed it. I'm ok doing the manual deallocation of the objects. As a matter of fact, my plan was to force the user to do that and had already implemented code for that. 

Thanks you for all your help. I'll close the issue.

**Comment by marcobambini** [comment] 2022-03-06 08:11
@untoldengine can I close this issue?

**Closed** 2022-03-06 14:03 UTC
